version: '3.7'

services:
  nginx:
    init: true
    container_name: nginx
    build: requirements/nginx
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress-volume:/var/www/html/
    depends_on:
      - wordpress
    restart: always

  wordpress:
    init: true
    container_name: wordpress
    build:
      context: requirements/wordpress
      args:
        - DB_NAME=$DB_NAME
        - DB_USER=$DB_USER
        - DB_PASSWORD=$DB_PASSWORD
        - DB_HOST=$DB_HOST
    networks:
      - inception
    ports:
      - "9000:9000"
    volumes:
      - wordpress-volume:/var/www/html/
    depends_on:
      - mariadb
    restart: always

  mariadb:
    init: true
    container_name: mariadb
    build:
      context: requirements/mariadb
      args:
        - DB_NAME=$DB_NAME
        - DB_USER=$DB_USER
        - DB_PASSWORD=$DB_PASSWORD
        - DB_ROOT=$DB_ROOT
    networks:
      - inception
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    restart: always

volumes:
  wordpress-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/db

networks:
  inception:
    driver: bridge