version: '3'

services:
  nginx:
    container_name: nginx
    build: requirements/nginx
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - wordpress-volume:/var/www/html/
    depends_on:
      - wordpress
    restart: always

  wordpress:
    container_name: wordpress
    build: requirements/wordpress
    networks:
      - inception
    volumes:
      - wordpress-volume:/var/www/html/
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always

  mariadb:
    container_name: mariadb
    build: requirements/mariadb
    networks:
      - inception
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
    env_file:
      - .env
    restart: always

volumes:
  wordpress-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/wordpress
  db-volume:
    driver_opts:
      o: bind
      type: none
      device: /home/${USER}/data/db

networks:
  inception:
    driver: bridge